title: "2025 HSHS basic of Bioinformation"
description: "with Biopython"
url: "https://suimaire.github.io"

# ----------------
# ğŸ‘‡ í…Œë§ˆ ë¡œë“œ ë°©ì‹ ë³€ê²½
theme: null

plugins:
  - just-the-docs

just_the_docs:
  heading_numbers: true
  heading_number_levels: 4

# ê¸°ì¡´ nav_order ë“±ì€ ê·¸ëŒ€ë¡œ ë‘ì‹œë©´ ë©ë‹ˆë‹¤
nav_order:
  - Home: index.md
  - Day 1
  - Day 2
  - Day 3
  - Day 4
  - Day 5
  - Assignments: assignments.md
  - Syllabus: syllabus.md
